/**
 * Downloads the SHACL TBox from datashapes.org and writes it to public/tbox.ttl.
 *
 * Usage:
 *   node scripts/extract-tbox.mjs
 *   node scripts/extract-tbox.mjs --source https://datashapes.org/schema.ttl
 *   node scripts/extract-tbox.mjs --output public/tbox.ttl
 */

import { writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const args = process.argv.slice(2);
function getArg(name, fallback) {
  const index = args.indexOf(`--${name}`);
  return index >= 0 && args[index + 1] ? args[index + 1] : fallback;
}

const SOURCE_URL = getArg("source", "https://datashapes.org/schema.ttl");
const OUTPUT_PATH = getArg("output", resolve(__dirname, "../public/tbox.ttl"));

async function main() {
  console.log(`[tbox] fetching ${SOURCE_URL} ...`);
  const response = await fetch(SOURCE_URL);
  if (!response.ok) {
    throw new Error(`Failed to fetch TBox: ${response.status} ${response.statusText}`);
  }
  const turtle = await response.text();
  console.log(`[tbox] received ${(turtle.length / 1024).toFixed(0)} KB of Turtle`);

  const header = [
    "# ┌──────────────────────────────────────────────────────────────────────┐",
    `# │ This file is AUTO-GENERATED by scripts/extract-tbox.mjs              │`,
    `# │ Source: ${SOURCE_URL.padEnd(58)}│`,
    "# │ DO NOT EDIT — run the script to regenerate.                          │",
    "# └──────────────────────────────────────────────────────────────────────┘",
    "",
  ].join("\n");

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, header + turtle, "utf-8");
  console.log(`[tbox] wrote ${OUTPUT_PATH} (${((header.length + turtle.length) / 1024).toFixed(1)} KB)`);
}

main().catch((err) => {
  console.error("[tbox] FATAL:", err.message);
  process.exit(1);
});
