name: Check dependencies

on:
  push:
  pull_request:

jobs:
  depcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npx depcheck --ignores="@types/*,eslint-*,globals,vitest,@vitejs/*,typescript,typescript-eslint,vite,@ldo/solid,buffer,shexj,@vitest/coverage-v8,@testing-library/user-event" --ignore-dirs="dist,node_modules"
